name: Todo_Jeact

on:
  push:
    branches: [main, develope]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      name: First step
      run: npm install
        npm test
        npm build
